### ISSUE TITLE
Schema model description

### ISSUE THREAD

**Issue by supersonicclay** [Mermade/widdershins#105]
Not sure if this belongs in this repo or in [shins](https://github.com/Mermade/shins).

I'd like to have descriptions visible for each of my models (like swagger-ui does).

Current:
![image](https://user-images.githubusercontent.com/469582/38534039-2682846e-3c39-11e8-9aee-1d1aaa7b60fd.png)

Desired:
![image](https://user-images.githubusercontent.com/469582/38534011-0b72184c-3c39-11e8-830b-7b09ba57f222.png)

**Comment by MikeRalphson** [comment]
Should be fixed in v3.2.1 - many thanks for reporting.

**Comment by geld0r** [comment]
I just saw this after updating but was wondering why the order is:

```
[Enity Name]
Properties
[Enity Description]
```

and not

```
[Enity Name]
[Enity Description]
Properties
```

Seems a bit weird this way because "Properties" is no longer the heading for the properties.

**Comment by JLNNN** [comment]
I can confirm that the entity description is visible again but in incorrect order :) (Like @geld0r said.)

**Comment by MikeRalphson** [comment]
Fix to positioning of the `Properties` header included in v3.2.2 thanks @supersonicclay

**Comment by geld0r** [comment]
Just tried to verify this with v3.3.0 but the issue still persists. Did this accidentally get lost or did the issue come up again in the meantime?

**Comment by geld0r** [comment]
Nevermind, forgot to update my overridden templates. My bad. With that it looks good!
